version: "3.6"

services: 
  php:
    image: bitnami/php-fpm:8.0
    volumes:
      - ./src:/app
      - ./php/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema
    volumes: 
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "3000:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  apache:
    image: bitnami/apache:2.4
    depends_on:
      - php
    volumes:
      - ./src:/app
      - ./apache/my_vhost.conf:/vhosts/myapp.conf:ro
      - ./apache/certs:/certs
    ports:
    - "8000:8080"
